server:
  port: 8085

#nacos配置
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-map
  #redis的配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

amap:
  key: 913695d50e30fec17ec162e57bc3eb96