server:
  port: 8081

#nacos配置
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: api-passenger
  #redis的配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
logging:
  level:
    com.ling: debug